import type { Metadata } from "next";
import Navbar from "@/components/main_components/navbar/Navbar";
import { NextUIProvider } from "@nextui-org/react";
import localFont from "next/font/local";
import "./globals.css";
const yekan = localFont({
  src: [
    {
      path: "../../public/fonts/Yekan.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className={yekan.className}>
        <NextUIProvider className="fixed z-10 w-full">
          <Navbar />
        </NextUIProvider>
        <div  className="w-full h-[175px]"/>
        {children}
        <div className="h-screen">
          
        </div>
      </body>
    </html>
  );
}
